### ISSUE TITLE
API Version needs to be updated

### ISSUE THREAD

**Issue by mikepaisner** [sorenkrabbe/Chrome-Salesforce-inspector#221]
Inspector is my favorite Salesforce tool, but it appears to be stuck on an older API version.  I think it is at API 51.0.  This means it can't access some standard fields that have been introduced recently.   For example, it doesn't recognize the field PermissionsBypassMFAForUiLogins in the query because it was just recently introduced by Salesforce:

SELECT Id, Name, PermissionsBypassMFAForUiLogins FROM PermissionSet

Is there a way to update Inspector to a more recent API version?

**Comment by tprouvot** [comment]
Hi @mikepaisner 
Unfortunately the pull requests to update API version are not accepted.
I created a fork to perform the API updates and fix some issues.

You could find it here:
https://github.com/tprouvot/Chrome-Salesforce-inspector

You can find the instructions on how to add this extension to chrome in the readme.
Please let me know if you have some troubles for installing it.

**Comment by mikepaisner** [comment]
I’m running into issues trying to install this fork.

Any idea of when this will be released with the new API version?

Regards,
Mike

**Comment by tprouvot** [comment]
Hi @mikepaisner,.
I think it won't be updated.

What's are the issues you're facing? Maybe I could help you to solve it.

**Comment by mikepaisner** [comment]
When I was trying build the following SOQL query, it did not autocomplete the field “PermissionsBypassMFAForUiLogins”

SELECT Id, Name, PermissionsBypassMFAForUiLogins FROM PermissionSet

I was thinking that the field was not available due to the Inspector API version.  However, if I type out the field name, it does perform the query as expected, so this isn’t as big a problem as I thought.

It would be nice if it autocompleted this fieldname like other fieldnames.  I don’t understand why autocomplete is not working for this query.

Regards,
Mike

**Comment by jesperkristensen** [comment]
I merged the PR and published a new version. Hopefully it won't take too long to appear in the Chrome and Firefox stores.

**Comment by mikepaisner** [comment]
@jesperkristensen  - Chrome store is still showing V1.12.  Can you push V1.13 to Chrome store?

**Comment by jesperkristensen** [comment]
Yes, we update the version number before we push it to the stores. I only have access to push to the Firefox store. @sorenkrabbe  has access to push to the Chrome store.

**Comment by mikepaisner** [comment]
@sorenkrabbe - Would you mind pushing V1.13 to the Chrome store?
Thanks!
Mike

**Comment by Security-Zen** [comment]
@sorenkrabbe - Still waiting for Salesforce Inspector V1.13 in Chrome store.  Can you help?
Thanks,
Mike
